### ISSUE TITLE
Desconto em saldo diferenciado

### ISSUE THREAD

**Issue by plannersistemas** [ThiagoSousaGarcia/SolidPattern_Java#3]
oi @ThiagoSousaGarcia 

https://github.com/ThiagoSousaGarcia/SolidPattern_Java/blob/864df6dd2d679523935ab76eb5cd97e850484ba0/isp/ContaPessoaFisica.java#L9

Existe uma necessidade de que `ContaPessoaFisica` quando o saldo for maior que $2896 tenha um desconto de 25%.

Como podemos resolver esse problema usando interfaces

**Comment by ThiagoSousaGarcia** [comment]
Tenho uma dúvida sobre essa issue, pensei em duas soluções, seguindo abaixo elas: 

Na primeira, eu apenas criaria apenas uma condição no método **descontofisica** da classe **ContaPessoaFisica**, onde ao receber o saldo verificaria se ele é maior que 2896, eu descontaria 25%, caso contrário continuaria a descontar os 20%.

Na segunda solução eu criaria uma interface **InterfaceFisicaMaiorDesconto**, onde criaria o método **maiordesconto**, para tratar individualmente este caso do desconto de 25%, logo a classe **ContaPessoaFisica** iria implementar **InterfaceFisicaMaiorDesconto** e **InterfaceFisica**.

Qual deveria ser usada ?

**Comment by plannersistemas** [comment]
@ThiagoSousaGarcia pensa que amanhã possa aparecer uma nova regra a ser implementada para quem tenha saldo maior que $5000,00, colocar mais um **if** talvez não seja a melhor saída, pensa em algo que possamos evoluir, talvez o encapsulamento dessa regra em uma outra classe `CaculadoraDescontoPessoaFisica`

**Comment by ThiagoSousaGarcia** [comment]
Beleza, entendi, irei resolver;

**Comment by ThiagoSousaGarcia** [comment]
Issue resolvida.

**Comment by plannersistemas** [comment]
ok
